# Generated by Django 5.1.2 on 2026-02-05 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('priority', models.IntegerField(default=5, verbose_name='任务优先级')),
                ('max_retries', models.IntegerField(default=3, verbose_name='最大重试次数')),
                ('retry_delay', models.IntegerField(default=60, verbose_name='重试延迟(秒)')),
                ('condition_field', models.CharField(blank=True, max_length=100, verbose_name='条件字段名')),
                ('condition_value', models.CharField(blank=True, max_length=255, verbose_name='条件值')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('periodic_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_schedule', to='django_celery_beat.periodictask')),
            ],
            options={
                'verbose_name': '自定义调度配置',
                'verbose_name_plural': '自定义调度配置',
                'db_table': 't_custom_schedule',
            },
        ),
    ]
