# Generated by Django 5.1.2 on 2026-01-12 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomIntervalSchedule',
            fields=[
                ('intervalschedule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.intervalschedule')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('createUser', models.CharField(max_length=20, null=True, verbose_name='创建人')),
                ('updateUser', models.CharField(max_length=20, null=True, verbose_name='修改人')),
                ('displayName', models.CharField(max_length=200, verbose_name='显示名称')),
            ],
            options={
                'db_table': 't_interval',
            },
            bases=('django_celery_beat.intervalschedule', models.Model),
        ),
        migrations.CreateModel(
            name='CustomPeriodicTask',
            fields=[
                ('periodictask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.periodictask')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('createUser', models.CharField(max_length=20, null=True, verbose_name='创建人')),
                ('updateUser', models.CharField(max_length=20, null=True, verbose_name='修改人')),
                ('customInterval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='celery_task.customintervalschedule', verbose_name='自定义调度器')),
            ],
            options={
                'db_table': 't_task',
            },
            bases=('django_celery_beat.periodictask', models.Model),
        ),
    ]
