# Generated by Django 5.1.2 on 2026-01-13 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celery_task', '0001_initial'),
        ('django_celery_beat', '0019_alter_periodictasks_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomClockedSchedule',
            fields=[
                ('clockedschedule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.clockedschedule')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('createUser', models.CharField(max_length=20, null=True, verbose_name='创建人')),
                ('updateUser', models.CharField(max_length=20, null=True, verbose_name='修改人')),
            ],
            options={
                'db_table': 't_clocked_schedule',
            },
            bases=('django_celery_beat.clockedschedule', models.Model),
        ),
        migrations.CreateModel(
            name='CustomCrontabSchedule',
            fields=[
                ('crontabschedule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.crontabschedule')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('createUser', models.CharField(max_length=20, null=True, verbose_name='创建人')),
                ('updateUser', models.CharField(max_length=20, null=True, verbose_name='修改人')),
            ],
            options={
                'db_table': 't_crontab_schedule',
            },
            bases=('django_celery_beat.crontabschedule', models.Model),
        ),
        migrations.CreateModel(
            name='CustomSolarSchedule',
            fields=[
                ('solarschedule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.solarschedule')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('createUser', models.CharField(max_length=20, null=True, verbose_name='创建人')),
                ('updateUser', models.CharField(max_length=20, null=True, verbose_name='修改人')),
            ],
            options={
                'db_table': 't_solar_schedule',
            },
            bases=('django_celery_beat.solarschedule', models.Model),
        ),
        migrations.AddField(
            model_name='customperiodictask',
            name='customClocked',
            field=models.ForeignKey(blank=True, help_text='Clocked Schedule to run the task on.  Set only one schedule type, leave the others null.', null=True, on_delete=django.db.models.deletion.CASCADE, to='celery_task.customclockedschedule', verbose_name='Clocked Schedule'),
        ),
        migrations.AddField(
            model_name='customperiodictask',
            name='customCrontab',
            field=models.ForeignKey(blank=True, help_text='Crontab Schedule to run the task on.  Set only one schedule type, leave the others null.', null=True, on_delete=django.db.models.deletion.CASCADE, to='celery_task.customcrontabschedule', verbose_name='Crontab Schedule'),
        ),
        migrations.AddField(
            model_name='customperiodictask',
            name='customSolar',
            field=models.ForeignKey(blank=True, help_text='Solar Schedule to run the task on.  Set only one schedule type, leave the others null.', null=True, on_delete=django.db.models.deletion.CASCADE, to='celery_task.customsolarschedule', verbose_name='Solar Schedule'),
        ),
    ]
