# Generated by Django 5.1.2 on 2026-01-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'DEBUG'), ('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR'), ('CRITICAL', 'CRITICAL')], db_index=True, max_length=10)),
                ('logger_name', models.CharField(db_index=True, max_length=100)),
                ('message', models.TextField()),
                ('module', models.CharField(blank=True, max_length=100, null=True)),
                ('func_name', models.CharField(blank=True, max_length=100, null=True)),
                ('line_no', models.IntegerField(blank=True, null=True)),
                ('thread', models.CharField(blank=True, max_length=50, null=True)),
                ('process', models.CharField(blank=True, max_length=50, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, null=True)),
                ('exception_info', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': '日志条目',
                'verbose_name_plural': '日志条目',
                'db_table': 'log_entry',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'level'], name='log_entry_created_c328bc_idx'), models.Index(fields=['logger_name', '-created_at'], name='log_entry_logger__e2a1e3_idx'), models.Index(fields=['level', '-created_at'], name='log_entry_level_6fec27_idx')],
            },
        ),
    ]
