# Generated by Django 5.1.2 on 2025-06-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0003_alter_httpcasemodel_casename'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuitModel',
            fields=[
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('createUser', models.CharField(max_length=20, null=True, verbose_name='创建人')),
                ('updateUser', models.CharField(max_length=20, null=True, verbose_name='修改人')),
                ('suitId', models.IntegerField(primary_key=True, serialize=False, verbose_name='套件Id')),
                ('suitName', models.CharField(max_length=50, verbose_name='套件名')),
                ('caseList', models.ManyToManyField(blank=True, related_name='suit', to='cases.httpcasemodel')),
            ],
            options={
                'db_table': 't_suit',
            },
        ),
    ]
