# Generated by Django 5.1.2 on 2026-02-05 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuitCaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_order', models.IntegerField(help_text='用例在套件中的执行顺序，数字越小越先执行', verbose_name='执行顺序')),
                ('is_first', models.BooleanField(default=False, help_text='标记为最先执行的用例', verbose_name='是否最先执行')),
                ('is_last', models.BooleanField(default=False, help_text='标记为最后执行的用例', verbose_name='是否最后执行')),
                ('is_stream', models.BooleanField(default=False, verbose_name='是否为循环请求')),
                ('streamKey', models.CharField(max_length=300, null=True, verbose_name='流式key')),
                ('globalMap', models.JSONField(null=True, verbose_name='全局变量')),
                ('changeSidKey', models.CharField(max_length=300, null=True, verbose_name='要切换的会话ID')),
                ('changeSid', models.BooleanField(default=False, verbose_name='要切换ID的key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.httpcasemodel', verbose_name='用例')),
            ],
            options={
                'db_table': 't_suit_case',
                'ordering': ['execution_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SuitModel',
            fields=[
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('createUser', models.CharField(max_length=20, null=True, verbose_name='创建人')),
                ('updateUser', models.CharField(max_length=20, null=True, verbose_name='修改人')),
                ('suitId', models.IntegerField(primary_key=True, serialize=False, verbose_name='套件Id')),
                ('suitName', models.CharField(max_length=50, verbose_name='套件名')),
                ('casesList', models.ManyToManyField(blank=True, related_name='suit', through='automatic.SuitCaseModel', to='cases.httpcasemodel')),
            ],
            options={
                'db_table': 't_suit',
            },
        ),
        migrations.AddField(
            model_name='suitcasemodel',
            name='suit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automatic.suitmodel', verbose_name='套件'),
        ),
        migrations.AlterUniqueTogether(
            name='suitcasemodel',
            unique_together={('suit', 'case')},
        ),
    ]
