# Generated by Django 5.1.2 on 2025-12-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suitcasemodel',
            name='globalList',
            field=models.JSONField(default=list, verbose_name='全局变量'),
        ),
    ]
