# Generated by Django 5.1.2 on 2025-12-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatic', '0002_suitcasemodel_globallist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suitcasemodel',
            name='globalList',
            field=models.JSONField(verbose_name='全局变量'),
        ),
    ]
