# Generated by Django 5.1.2 on 2025-12-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatic', '0003_alter_suitcasemodel_globallist'),
    ]

    operations = [
        migrations.AddField(
            model_name='suitcasemodel',
            name='is_stream',
            field=models.BooleanField(default=False, verbose_name='是否为流式请求'),
        ),
    ]
