# Generated by Django 5.1.2 on 2025-12-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatic', '0004_suitcasemodel_is_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='suitcasemodel',
            name='streamKey',
            field=models.CharField(default=None, max_length=300, verbose_name='流式key'),
        ),
    ]
