# Generated by Django 5.1.2 on 2025-12-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatic', '0005_suitcasemodel_streamkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suitcasemodel',
            name='streamKey',
            field=models.CharField(max_length=300, null=True, verbose_name='流式key'),
        ),
    ]
