# Generated by Django 5.1.2 on 2025-12-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatic', '0006_alter_suitcasemodel_streamkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suitcasemodel',
            name='globalList',
            field=models.JSONField(default={}, verbose_name='全局变量'),
        ),
    ]
