# Generated by Django 5.1.2 on 2025-12-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatic', '0007_alter_suitcasemodel_globallist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suitcasemodel',
            name='globalList',
            field=models.JSONField(null=True, verbose_name='全局变量'),
        ),
    ]
