# Generated by Django 5.1.2 on 2025-09-29 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressItem',
            fields=[
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('createUser', models.CharField(max_length=20, null=True, verbose_name='创建人')),
                ('updateUser', models.CharField(max_length=20, null=True, verbose_name='修改人')),
                ('expressItemId', models.IntegerField(primary_key=True, serialize=False, verbose_name='规则组id')),
            ],
            options={
                'db_table': 't_express_item',
            },
        ),
        migrations.CreateModel(
            name='OneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testOne', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'one_model',
            },
        ),
        migrations.CreateModel(
            name='Expresses',
            fields=[
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('createUser', models.CharField(max_length=20, null=True, verbose_name='创建人')),
                ('updateUser', models.CharField(max_length=20, null=True, verbose_name='修改人')),
                ('expressId', models.IntegerField(primary_key=True, serialize=False, verbose_name='表达式id')),
                ('matchKey', models.CharField(help_text='需要校验value的key', max_length=100, verbose_name='key')),
                ('keyType', models.CharField(default='str', help_text='key对应value的类型', max_length=30, verbose_name='key的类型')),
                ('matchMethod', models.CharField(max_length=200, null=True, verbose_name='取值方法')),
                ('matchValue', models.CharField(max_length=200, verbose_name='预期答案')),
                ('matchOper', models.CharField(help_text='运算符', max_length=10, verbose_name='运算符')),
                ('expressItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expressList', to='cases.expressitem')),
            ],
            options={
                'db_table': 't_expresses',
            },
        ),
        migrations.CreateModel(
            name='HttpCaseModel',
            fields=[
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('createUser', models.CharField(max_length=20, null=True, verbose_name='创建人')),
                ('updateUser', models.CharField(max_length=20, null=True, verbose_name='修改人')),
                ('caseId', models.IntegerField(primary_key=True, serialize=False)),
                ('caseName', models.CharField(help_text='输入用例名', max_length=100, unique=True, verbose_name='用例名')),
                ('headers', models.JSONField(help_text='输入请求头部信息', null=True, verbose_name='请求头')),
                ('body', models.JSONField(help_text='输入请求体信息', null=True, verbose_name='请求体')),
                ('timeout', models.IntegerField(default=3, help_text='请输入超时时间', verbose_name='超时时间')),
                ('retries', models.IntegerField(default=1, help_text='输入重视次数', verbose_name='重试次数')),
                ('isCore', models.BooleanField(default=False, verbose_name='是否为核心用例')),
                ('globalList', models.JSONField(default=list, verbose_name='全局变量')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='httpcase', to='system.portmodel')),
            ],
            options={
                'db_table': 't_interface_httpcase',
            },
        ),
        migrations.AddField(
            model_name='expressitem',
            name='httpCase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expressItem', to='cases.httpcasemodel'),
        ),
        migrations.CreateModel(
            name='ThreeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testThree', models.CharField(max_length=30)),
                ('testMany', models.ManyToManyField(blank=True, null=True, related_name='three', to='cases.onemodel')),
            ],
            options={
                'db_table': 'three_model',
            },
        ),
        migrations.CreateModel(
            name='TwoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testTwo', models.CharField(max_length=30)),
                ('testFor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two', to='cases.onemodel')),
            ],
            options={
                'db_table': 'two_model',
            },
        ),
    ]
