# Generated by Django 5.1.2 on 2025-04-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testThree', models.CharField(max_length=30)),
                ('testMany', models.ManyToManyField(blank=True, null=True, related_name='three', to='cases.onemodel')),
            ],
            options={
                'db_table': 'three_model',
            },
        ),
    ]
