# Generated by Django 5.1.2 on 2025-11-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expresses',
            name='keyType',
            field=models.CharField(default='str', help_text='key对应value的类型', max_length=30, null=True, verbose_name='key的类型'),
        ),
        migrations.AlterField(
            model_name='expresses',
            name='matchMethod',
            field=models.CharField(default=0, max_length=200, verbose_name='取值方法'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expresses',
            name='matchOper',
            field=models.CharField(help_text='运算符', max_length=10, null=True, verbose_name='运算符'),
        ),
        migrations.AlterField(
            model_name='expresses',
            name='matchValue',
            field=models.CharField(max_length=200, null=True, verbose_name='预期答案'),
        ),
    ]
