# Generated by Django 5.1.2 on 2025-11-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_alter_expresses_keytype_alter_expresses_matchmethod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expresses',
            name='keyType',
            field=models.CharField(blank=True, default='str', help_text='key对应value的类型', max_length=30, null=True, verbose_name='key的类型'),
        ),
        migrations.AlterField(
            model_name='expresses',
            name='matchMethod',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='取值方法'),
        ),
        migrations.AlterField(
            model_name='expresses',
            name='matchOper',
            field=models.CharField(default=0, help_text='运算符', max_length=10, verbose_name='运算符'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expresses',
            name='matchValue',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='预期答案'),
        ),
    ]
