# Generated by Django 5.1.2 on 2025-05-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_threemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='httpcasemodel',
            name='caseName',
            field=models.CharField(help_text='输入用例名', max_length=100, unique=True, verbose_name='用例名'),
        ),
    ]
