# Generated by Django 5.1.2 on 2025-07-14 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_httpcasemodel_casename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expresses',
            name='matchValueType',
        ),
    ]
