# Generated by Django 5.1.2 on 2025-12-24 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_expresses_keytype_alter_expresses_matchmethod_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='httpcasemodel',
            name='globalList',
        ),
    ]
