# Generated by Django 5.1.2 on 2025-07-18 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_remove_expresses_matchvaluetype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='httpcasemodel',
            old_name='timeOut',
            new_name='timeout',
        ),
    ]
