# Generated by Django 5.1.2 on 2025-03-19 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartModel',
            fields=[
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('createUser', models.CharField(max_length=20, null=True, verbose_name='创建人')),
                ('updateUser', models.CharField(max_length=20, null=True, verbose_name='修改人')),
                ('departId', models.IntegerField(primary_key=True, serialize=False, verbose_name='部门ID')),
                ('departName', models.CharField(max_length=40, verbose_name='部门名')),
            ],
            options={
                'db_table': 't_depart',
            },
        ),
        migrations.CreateModel(
            name='PermissionModel',
            fields=[
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('createUser', models.CharField(max_length=20, null=True, verbose_name='创建人')),
                ('updateUser', models.CharField(max_length=20, null=True, verbose_name='修改人')),
                ('perId', models.AutoField(primary_key=True, serialize=False)),
                ('perCode', models.CharField(max_length=200, verbose_name='权限code')),
                ('synopsis', models.CharField(max_length=1000, null=True, verbose_name='简介')),
            ],
            options={
                'db_table': 't_permission',
            },
        ),
        migrations.CreateModel(
            name='ApplyModel',
            fields=[
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('createUser', models.CharField(max_length=20, null=True, verbose_name='创建人')),
                ('updateUser', models.CharField(max_length=20, null=True, verbose_name='修改人')),
                ('applyId', models.IntegerField(primary_key=True, serialize=False, verbose_name='应用Id')),
                ('applyName', models.CharField(max_length=100, unique=True, verbose_name='应用名')),
                ('baseUrl', models.CharField(max_length=200, unique=True, verbose_name='域地址')),
                ('synopsis', models.CharField(max_length=1000, null=True, verbose_name='简介')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply', to='system.departmodel')),
            ],
            options={
                'db_table': 't_apply',
            },
        ),
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('createUser', models.CharField(max_length=20, null=True, verbose_name='创建人')),
                ('updateUser', models.CharField(max_length=20, null=True, verbose_name='修改人')),
                ('groupId', models.AutoField(primary_key=True, serialize=False)),
                ('groupName', models.CharField(max_length=200, verbose_name='组名称')),
                ('synopsis', models.CharField(max_length=1000, null=True, verbose_name='简介')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.departmodel')),
                ('permission', models.ManyToManyField(blank=True, related_name='group', to='system.permissionmodel')),
            ],
            options={
                'db_table': 't_group',
            },
        ),
        migrations.CreateModel(
            name='PortModel',
            fields=[
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('createUser', models.CharField(max_length=20, null=True, verbose_name='创建人')),
                ('updateUser', models.CharField(max_length=20, null=True, verbose_name='修改人')),
                ('portId', models.IntegerField(primary_key=True, serialize=False, verbose_name='接口id')),
                ('portName', models.CharField(max_length=50, unique=True, verbose_name='接口名')),
                ('portPath', models.CharField(max_length=200, unique=True, verbose_name='接口地址')),
                ('synopsis', models.CharField(max_length=1000, null=True, verbose_name='简介')),
                ('apply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port', to='system.applymodel')),
            ],
            options={
                'db_table': 't_port',
            },
        ),
        migrations.CreateModel(
            name='RoleModel',
            fields=[
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('createUser', models.CharField(max_length=20, null=True, verbose_name='创建人')),
                ('updateUser', models.CharField(max_length=20, null=True, verbose_name='修改人')),
                ('roleId', models.AutoField(primary_key=True, serialize=False)),
                ('roleName', models.CharField(max_length=200, verbose_name='角色名')),
                ('synopsis', models.CharField(max_length=1000, null=True, verbose_name='简介')),
                ('permission', models.ManyToManyField(blank=True, related_name='role', to='system.permissionmodel')),
            ],
            options={
                'db_table': 't_role',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('createUser', models.CharField(max_length=20, null=True, verbose_name='创建人')),
                ('updateUser', models.CharField(max_length=20, null=True, verbose_name='修改人')),
                ('userId', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('userName', models.CharField(help_text='输入用户名', max_length=50, verbose_name='用户名')),
                ('email', models.EmailField(help_text='输入邮箱', max_length=50, unique=True, verbose_name='邮箱')),
                ('phone', models.CharField(help_text='输入手机号', max_length=20, unique=True, verbose_name='手机号')),
                ('password', models.CharField(help_text='输入密码', max_length=100, verbose_name='密码')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='system.departmodel')),
                ('groups', models.ManyToManyField(blank=True, related_name='user', to='system.groupmodel')),
                ('roles', models.ManyToManyField(blank=True, related_name='user', to='system.rolemodel')),
            ],
            options={
                'db_table': 't_user',
            },
        ),
    ]
