# Generated by Django 5.1.2 on 2025-04-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applymodel',
            name='owner',
            field=models.CharField(default='admin', max_length=200, verbose_name='负责人'),
        ),
    ]
