# Generated by Django 5.1.2 on 2025-04-30 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_applymodel_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('createUser', models.CharField(max_length=20, null=True, verbose_name='创建人')),
                ('updateUser', models.CharField(max_length=20, null=True, verbose_name='修改人')),
                ('menuId', models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='菜单ID')),
                ('menuName', models.CharField(max_length=50, unique=True, verbose_name='菜单名')),
                ('icon', models.CharField(default='Menu', max_length=20, verbose_name='图标')),
                ('path', models.CharField(default='/home', max_length=40)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.menu')),
                ('per', models.ManyToManyField(blank=True, related_name='menu', to='system.permissionmodel')),
            ],
            options={
                'ordering': ['-updatedDate'],
                'abstract': False,
            },
        ),
    ]
