# Generated by Django 5.1.2 on 2025-04-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menuId',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='菜单ID'),
        ),
    ]
