# Generated by Django 5.1.2 on 2025-05-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_alter_menu_menuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='sequence',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
    ]
