# Generated by Django 4.1.7 on 2024-09-30 08:04

from django.db import migrations, models
import django.db.models.deletion
import utils.random_number


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_user', models.CharField(max_length=20, verbose_name='创建人')),
                ('update_user', models.CharField(max_length=20, verbose_name='修改人')),
                ('depart_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='部门ID')),
                ('depart_name', models.CharField(max_length=30, verbose_name='部门名')),
            ],
            options={
                'db_table': 't_depart',
            },
            bases=(models.Model, utils.random_number.RandomNumber),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_user', models.CharField(max_length=20, verbose_name='创建人')),
                ('update_user', models.CharField(max_length=20, verbose_name='修改人')),
                ('p_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='权限id')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='权限名')),
            ],
            options={
                'db_table': 't_permission',
            },
            bases=(models.Model, utils.random_number.RandomNumber),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_user', models.CharField(max_length=20, verbose_name='创建人')),
                ('update_user', models.CharField(max_length=20, verbose_name='修改人')),
                ('role_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='角色id')),
                ('name', models.CharField(max_length=30, verbose_name='角色名')),
                ('permission', models.ManyToManyField(blank=True, related_name='role', to='common.permission')),
            ],
            options={
                'db_table': 't_role',
            },
            bases=(models.Model, utils.random_number.RandomNumber),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_user', models.CharField(max_length=20, verbose_name='创建人')),
                ('update_user', models.CharField(max_length=20, verbose_name='修改人')),
                ('menu_id', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='菜单id')),
                ('name', models.CharField(max_length=30, verbose_name='菜单名')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.menu')),
            ],
            options={
                'ordering': ['created_date'],
                'abstract': False,
            },
            bases=(models.Model, utils.random_number.RandomNumber),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_user', models.CharField(max_length=20, verbose_name='创建人')),
                ('update_user', models.CharField(max_length=20, verbose_name='修改人')),
                ('group_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='分组id')),
                ('name', models.CharField(max_length=30, verbose_name='分组名')),
                ('permission', models.ManyToManyField(blank=True, related_name='group', to='common.permission')),
            ],
            options={
                'db_table': 't_group',
            },
            bases=(models.Model, utils.random_number.RandomNumber),
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_user', models.CharField(max_length=20, verbose_name='创建人')),
                ('update_user', models.CharField(max_length=20, verbose_name='修改人')),
                ('appId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('appName', models.CharField(max_length=30, unique=True, verbose_name='应用名')),
                ('appType', models.CharField(choices=[(0, 'http'), (1, 'dubbo')], default=0, max_length=10, verbose_name='服务类型')),
                ('domains', models.URLField(unique=True, verbose_name='域名')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app', to='common.depart')),
            ],
            options={
                'db_table': 't_apply',
            },
            bases=(models.Model, utils.random_number.RandomNumber),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_user', models.CharField(max_length=20, verbose_name='创建人')),
                ('update_user', models.CharField(max_length=20, verbose_name='修改人')),
                ('user_id', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='用户id')),
                ('username', models.CharField(max_length=30, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='邮箱')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='手机号码')),
                ('group', models.ManyToManyField(blank=True, related_name='user', to='common.group')),
                ('permission', models.ManyToManyField(blank=True, related_name='user', to='common.permission')),
                ('role', models.ManyToManyField(blank=True, related_name='user', to='common.role')),
            ],
            options={
                'db_table': 't_user',
            },
            bases=(models.Model, utils.random_number.RandomNumber),
        ),
    ]
