# Generated by Django 4.1.7 on 2024-07-24 10:44

from django.db import migrations, models
import django.db.models.deletion
import utils.random_number


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_user', models.CharField(max_length=20, verbose_name='创建人')),
                ('update_user', models.CharField(max_length=20, verbose_name='修改人')),
                ('app_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('app_name', models.CharField(max_length=30, unique=True, verbose_name='应用名')),
                ('domains', models.URLField(unique=True, verbose_name='域名')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app', to='management.depart')),
            ],
            options={
                'db_table': 't_apply',
            },
            bases=(models.Model, utils.random_number.RandomNumber),
        ),
    ]
